#!/bin/bash
set -eo pipefail

NAME="$1"
TAG="$2"

if [[ -z "$TAG" ]]; then
  IMAGE=$NAME
else
  IMAGE=$NAME:$TAG
fi

SOURCE_IMAGE=$IMAGE
if [[ "$(docker images -q $IMAGE 2> /dev/null)" == "" ]]; then
  SOURCE_IMAGE="progrium/buildstep"
fi

# Place the app inside the container. If you already have app inside your tar, use /bin/bash -c "tar -x"
ID=$(cat | docker run -i -a stdin $SOURCE_IMAGE /bin/bash -c "mkdir -p /app && tar -xC /app")
test $(docker wait $ID) -eq 0
docker commit $ID $NAME $TAG > /dev/null

# Run the builder script and attach to view output
ID=$(docker run -d $IMAGE /build/builder)
docker attach $ID
test $(docker wait $ID) -eq 0
docker commit $ID $NAME $TAG > /dev/null
